spring:
  application.name: api-gateway-service
  profiles:
    active: home
  webflux:
    base-path: /home
server:
  port: 6100

logbook:
  format:
    style: http

logging:
  level:
    org.zalando.logbook: trace
